name: "Prerelease"
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'

concurrency:
  group: publish
  cancel-in-progress: false

jobs:
  Bump-Prerelease-Publish:
    name: Bump-Prerelease-Publish
    if: "!startsWith(github.event.head_commit.message, '[SKIP CI]') && !startsWith(github.event.head_commit.message, '[release]') && github.repository == 'subquery/subql-cosmos'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100
          token: ${{ secrets.REPO_TOKEN }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: marceloprado/has-changed-path@v1
        id: changed-types
        with:
          paths: packages/types

      - uses: marceloprado/has-changed-path@v1
        id: changed-common-cosmos
        with:
          paths: packages/common-cosmos

      - uses: marceloprado/has-changed-path@v1
        id: changed-node
        with:
          paths: packages/node

      - run: yarn

      - name: build
        run: yarn build

      #Add remove-stable-version
      - name: Bump types & deploy
        if: steps.changed-types.outputs.changed == 'true'
        uses: ./.github/actions/create-prerelease
        with:
          package-path: packages/types
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Bump common cosmos & deploy
        if: steps.changed-common-cosmos.outputs.changed == 'true'
        uses: ./.github/actions/create-prerelease
        with:
          package-path: packages/common-cosmos
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Bump node & deploy
        if: steps.changed-node.outputs.changed == 'true'
        uses: ./.github/actions/create-prerelease
        with:
          package-path: packages/node
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          message: '[SKIP CI] Prerelease'
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
