name: "Release"
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:

concurrency:
  # Same group as prerelease
  group: publish
  cancel-in-progress: false

jobs:

  # This gets the commit message because workflow dispatch doesnt set: github.event.head_commit.message
  pre-ci:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      commit-message: ${{ steps.step1.outputs.commit-message }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100

      # Get the commit message, workflow_dispatch doesn't contain it so we need to get it through git cli
      - id: step1
        run: |
          if [ -n "${{ github.event.head_commit.message }}" ]
          then
            echo "commit-message=${{ github.event.head_commit.message }}" | head -n 1 >> "$GITHUB_OUTPUT"
          else
            echo "commit-message=\"$(git log -1 --pretty=%B | head -n 1)\"" >> "$GITHUB_OUTPUT"
          fi

  Build-Publish:
    name: Build-Publish
    needs: pre-ci
    if: "!startsWith(needs.pre-ci.outputs.commit-message, '[SKIP CI]') && startsWith(needs.pre-ci.outputs.commit-message, '[release]') && github.repository == 'subquery/subql-cosmos'"
    runs-on: ubuntu-latest
    steps:
      #Check out
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18

    #Identify changes
      - uses: marceloprado/has-changed-path@v1
        id: changed-types
        with:
          paths: packages/types

      - uses: marceloprado/has-changed-path@v1
        id: changed-common-cosmos
        with:
          paths: packages/common-cosmos

      - uses: marceloprado/has-changed-path@v1
        id: changed-node
        with:
          paths: packages/node

      - run: yarn

      - name: build
        run: yarn build

      #Publish to npm and github releases
      - name: Publish Types
        if: steps.changed-types.outputs.changed == 'true'
        uses: ./.github/actions/create-release
        with:
          package-path: packages/types
          repo-token: ${{ secrets.REPO_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Publish Common cosmos
        if: steps.changed-common-cosmos.outputs.changed == 'true'
        uses: ./.github/actions/create-release
        with:
          package-path: packages/common-cosmos
          repo-token: ${{ secrets.REPO_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Publish Node
        if: steps.changed-node.outputs.changed == 'true'
        uses: ./.github/actions/create-release
        with:
          package-path: packages/node
          repo-token: ${{ secrets.REPO_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}
